insert into Gericht (gericht_id, name, beschreibung, preis) values
(1, 'Reis', 'vegan, mild, Asiatische Küche', 2.5),
(2, 'Spezialreis', 'vegan, scharf, Asiatische Küche', 3.0),
(3, 'Gemüsepfanne', 'vegan, mild, Asiatische Küche', 5.5),
(4, 'Gemüsepfanne mit Chilli', 'sehr scharf, vegan, Asiatische Küche', 6.5),
(5, 'Gemüsepfanne mit Hähnchen', 'mild, Asiatische Küche', 6.5),
(6, 'Penne mit Gemüse in Tomatensauce, ', 'vegetarisch, mild, Italienische Küche', 7.5),
(7, 'Bolognese', 'mild, Italienische Küche', 9.5),
(8, 'Antipasti', 'scharf, Italienische Küche', 3.5),
(9, 'Pizza Margherita', 'mild, vegetarisch, Italienische Küche', 10.5),
(10, 'Calzone', 'mild, Italienische Küche', 12.5),
(11, 'Gemüsesuppe mit Bockwurst', 'mild, Deutsche Küche', 6.5),
(12, 'Spätzle', 'mild, Deutsche Küche', 10.5),
(13, 'Fisch des Tages', 'Deutsche Küche, Fisch', 15.5),
(14, 'Flammenkuchen "Elsäßer"', 'mild, Deutsche Küche', 8.5),
(15, 'Steak des Tages', 'deutsche Küche', 18.5),
(16, 'Sushi', 'Japanische Küche', 10.5),
(17, 'Udon Nudelsuppe', 'Beilage', 8.5),
(18, 'Katsudon', 'Beilage', 9.5),
(19, 'Gyudon', 'Beilage', 11.5),
(20, 'Tempura', 'Beilage', 12.5);
